export const GrantsData = [
  {
    category: "DeFi Projects",
    tag: "FEATURED",
    title: "DeFi Protocol Development",
    amount: "$50,000 - $200,000",
    description: "Build lending, DEX, or yield farming protocols on Bitcoin Liberty L2",
    requirements: ["Smart contract development experience", "Security audit plan", "6+ month roadmap"],
    deadline: "Deadline: March 15, 2025",
    cta: "ACTIVE",
  },
  {
    category: "Developer Tools",
    tag: "OPEN",
    title: "Borrowing & Lending Protocol",
    amount: "$200,000-250,000",
    description: "Stand up a Borrowing and Lending V3 style AAVE project to assist in attractive more community",
    requirements: ["Smart Contract Audited by two auditing firms", "V3 Tech Stack"],
    deadline: "Deadline: October 15, 2025",
    cta: "ACTIVE",
  },
  {
    category: "Test Category",
    tag: "HIGH PRIORITY",
    title: "Test Bitcoin Project",
    amount: "100000",
    description: `This is a new NFT Launchpad that will allow users to create and manage their own NFT projects. It will also include a marketplace for "trading NFTs".`,
    requirements: ["Requirement 1", "Requirement 2", "Requirement 3"],
    deadline: "Deadline: 2024-12-31",
    cta: "ACTIVE",
  },
  {
    category: "Infrastructure",
    tag: "CLOSED",
    title: "Soccer Infrastructure",
    amount: "$50,000 - $200,000",
    description: "Create an award winning crypto soccer team formed by brazilian players.",
    requirements: ["15 Players"],
    deadline: "Deadline: September 30, 2025",
    cta: "INACTIVE",
  },
];
